image: gradle:jdk16

stages:
  - test
  - build

test:
  stage: test
  script:
    - ./gradlew test
  artifacts:
    paths:
      - build/test-results/test/**/TEST-*.xml
    reports:
      junit: build/test-results/test/**/TEST-*.xml

build:
  stage: build
  script:
    - ./gradlew assemble
