image: gradle:jdk16

stages:
  - code-quality
  - test
  - build

code-quality:
  stage: code-quality
  script:
    - ./gradlew spotBugsMain
  artifacts:
    paths:
      - build/reports/spotbugs/main.xml
    reports:
      codequality: build/reports/spotbugs/main.xml

test:
  stage: test
  script:
    - ./gradlew test
  artifacts:
    paths:
      - build/test-results/test/**/TEST-*.xml
    reports:
      junit: build/test-results/test/**/TEST-*.xml

build:
  stage: build
  script:
    - ./gradlew assemble
